Feature/us 23 create menu burger
WildCodeSchool-2024-09/JS-Nantes-P2-Spotywild pull request #24
Opened 2024-11-18 16:01 UTC by IbraAD44

2024-11-19 09:18 UTC, MrLootman commented
Tentative de fusion avec la branche `main`.
A corriger via le bouton Edit en haut à droite de cette page.

2024-11-20 08:10 UTC, MrLootman commented
Conflit avec la page d'Accueil à régler avant intégration de la branche.

2024-11-20 10:25 UTC, MrLootman requested changes
Cette pull request est invalide pour toutes les raisons nommées en commentaire.

Un conseil : Fait relire ton code par un ChatBOT pour corriger toutes les fautes d'orthographe avant de push.

2024-11-20 10:25 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +export default function Menumob() {
Nommage de fonction incorrect : Le composant devrait s'appeler `Menu`.

2024-11-20 10:25 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +  const [Shoumodel, setShoumodel] = useState(false);
Nommage incorrect.
Le state devrait être rédigé comme suit :
`const [showModel, setShowModel] = useState(false);`

2024-11-20 10:25 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +    <header className="ccontainer  flex">
Pourquoi deux lettres "c" au début de container, et pourquoi une classe flex détachée ?

2024-11-20 10:25 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +        <div className=" fixed">
Pourquoi y a-t-il des espaces au niveau des classNames ?
A retirer.

2024-11-20 10:25 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +              <a href={"./Home"}>Accueil</a>
Le `./` n'a pas de sens pour les `href`, puisqu'il s'agit du chemin d'une URL.

D'ailleurs, on n'utilise pas de balise `a` en React, mais une balise `Link` ou `NavLink`.

2024-11-20 10:25 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +          alt=""
L'attribut `alt` est vide. Ce n'est pas une bonne pratique. Il faut y placer un commentaire descriptif de l'image, pour des raisons d'accessibilité.

2024-11-20 10:25 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +          className="burgurm"
Cette className n'est pas correcte d'un point de vue syntaxique.

2024-11-20 10:25 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +        className="menus"
Pourquoi "menus" au pluriel ?

2024-11-20 10:25 UTC, MrLootman commented on client/src/components/menu-mobil/menu.css
> +}
Deux gros problèmes ici :

- On n'utilise pas l'élément :root dans un fichier aussi local que `menu.css`. Il faut que tes variables soient placées dans `global.css`.
- Les erreurs d'orthographe sont énormes (`--bagraoundh`), et à plusieurs endroits. Soit aussi rigoureux dans le nommage de tes propriétés que tu ne l'es dans la rédaction des valeurs.

2024-11-20 10:25 UTC, MrLootman commented on client/src/components/menu-mobil/menu.css
> +}
la balise a ne doit pas être utilisée globalement. En stylisant les choses de cette manière, le style global de l'application est impacté.

2024-11-20 15:13 UTC, MrLootman requested changes

2024-11-20 15:13 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
>            className="burgurm"
Tu n'as pas corrigé le nom de la className.

2024-11-20 15:13 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +          alt="imagLogo"
En l'état, le texte alternatif ne peut pas être lu par un lecteur d'écran.
L'attribut alt doit posséder comme valeur un texte intelligible, pouvant être lu par un lecteur d'écran pour les personnes malvoyantes.

2024-11-20 15:13 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
>        <div> </div>
Pourquoi y a-t-il un élément `div` vide ?

2024-11-20 15:13 UTC, MrLootman commented on client/src/components/menu-mobil/menu.css
>  .ccontainer {
Tu as bien modifié le nom de la classe, mais pas le selecteur CSS qui contient là encore deux lettres "c".

2024-11-20 16:00 UTC, MrLootman requested changes

2024-11-20 16:00 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +          className="burgur-menu"
Toujours pas.

`burger-menu` est la bonne orthographe.

2024-11-20 16:00 UTC, MrLootman commented on client/src/components/menu-mobil/menu.css
> +.burgur-menu {
Idem.

2024-11-20 16:00 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +        <div className=" fixed">
L'espace est toujours présent.

2024-11-20 16:00 UTC, MrLootman commented on client/src/components/menu-mobil/Menumob.tsx
> +          <ul className=" model ">
Ici aussi, des espaces sont présents. Il faut les retirer.

2024-11-20 16:00 UTC, MrLootman commented on client/src/components/menu-mobil/menu.css
> +}
Même problème.

2024-11-20 16:32 UTC, MrLootman requested changes

2024-11-20 16:32 UTC, MrLootman commented on client/src/components/menu-mobil/menu.css
> +}
La balise a n'a pas été supprimée.

2024-11-21 10:20 UTC, Jeremy-Mrz commented on client/src/components/menu-mobil/menu.css
> +.burgur-menu {
🤔🤔🤔🤔🤔🤔🤔🤔

2024-11-22 09:01 UTC, MrLootman approved these changes

2024-11-22 09:01 UTC, merged