Feature/us 36 audio
WildCodeSchool-2024-09/JS-Nantes-P2-Spotywild pull request #36
Opened 2024-11-26 12:58 UTC by DamienD44

Insh'Allah ça passe :-)

2024-11-26 15:18 UTC, Jeremy-Mrz requested changes

2024-11-26 15:18 UTC, Jeremy-Mrz commented on client/src/main.tsx
> +<<<<<<< HEAD
Vestige d'un merge conflict, il faut le supprimer

2024-11-26 15:18 UTC, Jeremy-Mrz commented on client/src/components/AudioPlayer/MusicPlayer.tsx
> +
Est ce que ton music player fonctionne ? Si ce n'est pas le cas, il faut supprimer ce component

2024-11-26 15:18 UTC, Jeremy-Mrz commented on client/src/main.tsx
> +// You can add more routes as you build out your app!
Il faut supprimer le code mort

2024-11-26 15:18 UTC, Jeremy-Mrz commented on client/src/main.tsx
> +>>>>>>> 966c24271bff77f60728a2165d2ecb71165986d1
Il faut supprimer les commentaires inutiles et enlever `>>>>>>> 966c24271bff77f60728a2165d2ecb71165986d1`

2024-11-26 15:18 UTC, Jeremy-Mrz commented on client/src/pages/Albums.tsx
> +>>>>>>> 966c24271bff77f60728a2165d2ecb71165986d1
Idem

2024-11-26 15:18 UTC, Jeremy-Mrz commented on client/src/types/musicSection.d.ts
> +  songs: [];
Il faut préciser le type de songs, un tableau de quoi ?

2024-11-26 15:18 UTC, DamienD44 commented on client/src/main.tsx
> +<<<<<<< HEAD
bien chef!

2024-11-27 10:08 UTC, Jeremy-Mrz commented on client/src/main.tsx
> +<<<<<<< HEAD
Tu n'as pas corrigé ?

2024-11-27 10:10 UTC, Jeremy-Mrz commented on client/src/main.tsx
> +// You can add more routes as you build out your app!
Idem

2024-11-27 10:10 UTC, Jeremy-Mrz commented
Il manque les corrections du `main.tsx`

2024-11-27 10:38 UTC, DamienD44 commented on client/src/main.tsx
> +<<<<<<< HEAD
Si c'est corrigé, j'ai fais tout ce que tu m'as demandé lol

2024-11-27 10:41 UTC, Jeremy-Mrz approved these changes

2024-11-27 10:41 UTC, merged