Feature 41 done.
WildCodeSchool-2024-09/JS-Nantes-P2-Spotywild pull request #40
Opened 2024-11-27 16:00 UTC by FabriceAtlan

2024-11-27 16:06 UTC, Jeremy-Mrz requested changes

2024-11-27 16:06 UTC, Jeremy-Mrz commented on client/src/components/AudioPlayer/MusicPlayer.css
Supprimer code mort

2024-11-27 16:06 UTC, Jeremy-Mrz commented on client/src/components/AudioPlayer/MusicPlayer.css
> +  margin: 0; */
Idem

2024-11-27 16:06 UTC, Jeremy-Mrz commented on client/src/components/AudioPlayer/MusicPlayer.css
> +  /* background-color: #007bff;
Idem

2024-11-27 16:06 UTC, Jeremy-Mrz commented on client/src/components/AudioPlayer/MusicPlayer.tsx
>  }
Déplacer l'interface dans votre fichier interface

2024-11-27 16:33 UTC, FabriceAtlan commented on client/src/components/AudioPlayer/MusicPlayer.css
Fait !

2024-11-27 16:33 UTC, FabriceAtlan commented on client/src/components/AudioPlayer/MusicPlayer.css
> +  margin: 0; */
Fait !

2024-11-27 16:33 UTC, FabriceAtlan commented on client/src/components/AudioPlayer/MusicPlayer.css
> +  /* background-color: #007bff;
Fait !

2024-11-27 16:33 UTC, FabriceAtlan commented on client/src/components/AudioPlayer/MusicPlayer.tsx
>  }
Fait !

2024-11-28 09:01 UTC, Jeremy-Mrz approved these changes

2024-11-28 09:01 UTC, merged